[package]
name = "watagasi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
wat = "*"

[features]
alloc = []
std = ["alloc"]
default = ["std"]
