[package]
name = "wasp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
path = "src/main.rs"
name = "wasp"

[dev-dependencies]
wat = "*"

[features]
alloc = []
std = ["alloc"]
default = ["std"]
